### ISSUE TITLE
[BUG] 404 Bad Request

### ISSUE THREAD

**Issue by kleeedolinux** [Vitor1-1Santana/CMSPTasksDoer#5]
set. 26, 2024 7:34:07 PM com.vitorsantana.cmsptasksdoer.CmspCommunicator sendRequest
SEVERE: Connection failed: 404 Bad Request
com.vitorsantana.cmsptasksdoer.HttpClientException: 404 Bad Request
	at com.vitorsantana.cmsptasksdoer.CmspCommunicator.sendRequest(CmspCommunicator.java:132)
	at com.vitorsantana.cmsptasksdoer.CmspCommunicator.checkAnswer(CmspCommunicator.java:125)
	at com.vitorsantana.cmsptasksdoer.cmspobjects.Question.singleQuestionAnswerer(Question.java:131)
	at com.vitorsantana.cmsptasksdoer.cmspobjects.Question.answerQuestion(Question.java:94)
	at com.vitorsantana.cmsptasksdoer.CMSPTasksDoer$1.lambda$run$0(CMSPTasksDoer.java:134)
	at java.base/java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:1085)
	at com.vitorsantana.cmsptasksdoer.CMSPTasksDoer$1.run(CMSPTasksDoer.java:129)

Exception in thread "Thread-0" java.lang.NullPointerException: Cannot invoke "java.net.http.HttpResponse.body()" because the return value of "com.vitorsantana.cmsptasksdoer.CmspCommunicator.sendRequest(java.net.http.HttpClient, java.net.http.HttpRequest)" is null
	at com.vitorsantana.cmsptasksdoer.CmspCommunicator.checkAnswer(CmspCommunicator.java:125)
	at com.vitorsantana.cmsptasksdoer.cmspobjects.Question.singleQuestionAnswerer(Question.java:131)
	at com.vitorsantana.cmsptasksdoer.cmspobjects.Question.answerQuestion(Question.java:94)
	at com.vitorsantana.cmsptasksdoer.CMSPTasksDoer$1.lambda$run$0(CMSPTasksDoer.java:134)
	at java.base/java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:1085)
	at com.vitorsantana.cmsptasksdoer.CMSPTasksDoer$1.run(CMSPTasksDoer.java:129)
![image](https://github.com/user-attachments/assets/80b866f3-c0b4-4011-9ad7-89448ec29ea7)

**Comment by Vitor1-1Santana** [comment]
Olá, apesar deste issue não ter muitos detalhes sobre o problema, eu consegui identificar. Infelizmente, devido como o meu programa funciona, este problema não pode ser 100% resolvido.

Para este programa funcionar, é essencial que nas questões das tarefas tenha o botão "VERIFICAR". Este botão permite o meu programa verificar todas as possibilidades de resposta de uma questão até acertar. Se uma tarefa não tem este botão, o meu programa não consegue "chutar até acertar", e dá este erro. Nó máximo que posso fazer é pular tarefas que não tem este botão, e fazer ele seguir para as próximas.

Sim eu vou deixar isso claro sobre o botão no repositório, agora que o programa está mais estável, vou conseguir investir mais tempo em organizar tudo isso.

**Comment by Vitor1-1Santana** [comment]
Arrumei no commit 3363f871859dc3f2aa323cf26b344d8cf8fa940c
